timeTracker/puncher/urls.py
from django.conf.urls import url

from . import views

app_name = "puncher"
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<checkpoint_id>[0-9]+)/punch/$', views.punch, name='punch'),
    url(r'^(?P<checkpoint_id>[0-9]+)/accepted/$', views.accepted, name='accepted'),
]

timeTracker/timeTracker/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^puncher/', include('puncher.urls')),
    url(r'^admin/', admin.site.urls),
]

timeTracker/puncher/models.py
from __future__ import unicode_literals

from django.db import models
from django.utils import timezone
import datetime

# Create your models here.
class clocking(models.Model):
    punch_id = models.AutoField(primary_key=True)
    checkPoint_id = models.IntegerField()
    person_id = models.IntegerField()
    clock_in = models.DateTimeField()
    clock_out = models.DateTimeField()

    def __str__(self):
        return str(self.punch_id)
    
    def was_checkin_recently(self):
        return self.clock_in >= timezone.now() - datetime.timedelta(days=1)
    
    def was_checkout_recently(self):
        return self.clock_out >= timezone.now() - datetime.timedelta(days=1)

class checkPoint(models.Model):
    checkpoint_id = models.IntegerField(primary_key=True)
    
    def __str__(self):
        return str(self.checkpoint_id)

class person(models.Model):
    person_id = models.IntegerField(primary_key=True)

    def __str__(self):
        return str(self.person_id)

timeTracker/puncher/views.py
from django.shortcuts import HttpResponseRedirect, get_object_or_404, render
from django.urls import reverse

from puncher.models import clocking

# Create your views here.

def index(request):
    context = {'dummy': " - Let's go! - "}
    return render(request, 'puncher/index.html', context)

def punch(request, checkpoint_id):
    c = get_object_or_404(clocking, pk=checkpoint_id)
    print c.checkPoint_id
    return HttpResponseRedirect(reverse('puncher:accepted', args=(c.punch_id,)))

def accepted(request, checkpoint_id):
    context = {'dummy': " Checkpoint # "+str(checkpoint_id)+" - Well done! -"}
    return render(request, 'puncher/accepted.html', context)

timeTracker/puncher/templates/puncher/accepted.html
{% load static %}

<!DOCTYPE html>
<html>
    <body>
        <h2>Scanned! {{ dummy }}</h2>
    </body>
</html>

timeTracker/puncher/templates/puncher/index.html
{% load static %}

<!DOCTYPE html>
<html>
    <body>
        <h2>Scan it with your mobile! {{ dummy }}</h2>
        <img src="{% static 'puncher/images/qrcode.png' %}" alt="QR code" > 
    </body>
</html>

timeTracker/puncher/templates/puncher/punch.html
<h1>{{ clocking.punch_id }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'puncher:punch' clocking.punch_id %}" method="post">
{% csrf_token %}
    <ul>
        <li>
            <label for="checkpoint_id">Checkpoint id: </label>
            <input id="puncher_name" type="text" name="checkpoint_name" value="{{ clocking.checkPoint_id }}">
        </li>
        
        <li>
            <label for="person_id">Person id: </label>
            <input id="person_name" type="text" name="person_name" value="{{ clocking.person_id }}">
        </li>
    </ul>

<input type="submit" value="Check" />

</form>